version: "3.3"
services:
    noogle:
        image: mtik00/noogle:latest
        env_file: .env
        environment:
            - NOOGLE_GENERAL__BASE_CONFIG_FOLDER=/usr/src/app
            # - NOOGLE_GENERAL__DEBUG=1
        volumes:
            - ".secrets/data:/usr/src/app/data"
            - ".secrets/tokens:/usr/src/app/tokens"
            - ".secrets/logs:/usr/src/app/logs"
        build: .
        command: ["service", "both", "--once"]
